### ISSUE TITLE
Implement ingestion methods

### ISSUE THREAD

**Issue by aadroher** [codegram/sonic-client#4]
- [ ] Define typespecs / behaviour for public functions
- [x] Insert data in the index `PUSH <collection> <bucket> <object> "<text>"`
- [ ] Insert data in the index for a specific locale using `[LANG(<locale>)]?`
- [x] Count indexed elements `COUNT <collection> [<bucket> [<object>]?]?`
- [x] Flush all data from a collection `FLUSHC <collection>`
- [ ] Flush all data from a bucket `FLUSHB <collection> <bucket>`

**Comment by aadroher** [comment]
As mentioned in the description of https://github.com/codegram/elixir-sonic-client/pull/14, the scope of this has been reduced, for now, to the basic implementation of the checked boxes in the description of this task.

**Comment by aadroher** [comment]
Will create new tickets for both the outstanding items and additional issues when developing for this one.
