### ISSUE TITLE
Implement search methods

### ISSUE THREAD

**Issue by aadroher** [codegram/sonic-client#5]
- [x]  Define typespecs / behaviour for public functions
- [x] Search in the database `QUERY <collection> <bucket> "<terms>"`
- [x] Limit search items using `[LIMIT(<count>)]`
- [x] Offset search items using `[OFFSET(<count>)]`
- [x] Suggestion to autocomplete word `SUGGEST <collection> <bucket> "<word>" [LIMIT(<count>)]?`

**Comment by aadroher** [comment]
Put on hold while waiting for enough of https://github.com/codegram/elixir-sonic-client/issues/4 to be implemented.
